### PR TITLE
Fixed issue for #151 by adding 'from baboon import routes' to baboon/__init__.py

### LINKED ISSUE #151: When spinning 'dev' env, the web app on 'http://0.0.0.0:5000/' is not reachable

### PR DESCRIPTION
**Pull request by IlanZuckerman**
Fix #151

### CODE REVIEW

**Comment by IlanZuckerman** [comment]
NOTE: I added '# flake8: noqa' before the import to avoid flake8 failing the CI.
Flake8 complains about that it should be on top of file. but moving it at the top fails the application to run.

**Review by ipolonsk — COMMENTED** [review]
LGTM

**Comment by lioramilbaum** [comment]
I don't understand how this change is fixing the problem

**Comment by IlanZuckerman** [comment]
> I don't understand how this change is fixing the problem

Well, frankly speaking - me too.
But it was working fine before i accidentally removed the import.
And it is working now as well (with CI passing) after i reverted back this import.

**Review by lioramilbaum — APPROVED** [review]

**Pull request merged**
