### PR TITLE
added team's ssh keys and copy them to the server

### LINKED ISSUE #194: Find ssh connection method to give the ability for everybody to ssh to the VM.
We are missing the option of ssh into the VM from each project member computer. 
Right now, only the member who created the VM (production deployment at AWS) can ssh into the VM because Vagrant copies only his public key to the new VM.
Few options on how to achieve it:
a. Find out if Vagrant can copy multiple keys using the AWS plugin.
b. Create a file that will hold all of our keys in it, and during the bootstrap, copy this file to /user/ubuntu/.ssh/authorized_keys.
c. FInd out if AWS gives an automatic option for each new VM created to have those X keys deployed on the VM.

### PR DESCRIPTION
**Pull request by ipolonsk**
fix #194 
Added one command to the bootstrap.sh to copy the content of our "ssh-keys" to authorized_keys of the user 'ubuntu'.
The file "ssh-keys" holds Ilana's and Ilan's public keys and located on the main path.
After running a new VM with those settings I was able to ssh to it. (just 'ssh ubuntu@IP')

### CODE REVIEW

**Review by lioramilbaum — APPROVED** [review]
It is good for now, but, it is not scale able. The keys should be consumed from a key/value store. Let's file an issue to take care of it in the future.

**Comment by lioramilbaum** [comment]
Are you able to add tests which validates that the change work?

**Comment by ipolonsk** [comment]
1.Can you please explain the key/value store solution? Is there an open-source project or technology that does something similar? so I can read about it.
2. What do we want the test to check? is it the content of the file? because I'm not sure how can we simulate an ssh connection with private and public from a tried side server (GitHub runner).

**Comment by lioramilbaum** [comment]
> edited after I saw the recording:
> I'm not sure why this solution is not scalable? if a new member is joining he will need to add his key to one single file and redeploy the VM. (like any production environment that has a release version and being redeployed with the new repo code).

Is it reasonable to spin a new production environment in the following cases:
- a new member joins the team
- a team member left the team
- a team member ssh key was compromised

> 1.About the key/value store solution, Is there an open-source project or technology that uses this in their production? I can't understand why in our case this will be helpful for deploying ssh keys(will take the overhead of creating a DB and maintain it just to keep the value in key/value format, the information is not sensitive).

key/value store is not used for sensitive data. Examples of key/value stores: Openshift ConfigMap resources, Hashicorp consul

> 2. What do we want the test to check? is it the content of the file? because I'm not sure how can we simulate an ssh connection with private and public from a tried side server (GitHub runner).

Generate another key used by the CI only and verify that ssh is working.

**Review by lioramilbaum — APPROVED** [review]

**Pull request merged**
