### PR TITLE
Adding mariadb as a separate container to use as a DB with our web app

### LINKED ISSUE #216: Install the chosen DB type on a new container
**Bear in mind the following:**
- Appropriate Base docker container Should be used to run the DB. Investigate the existing containers on the docker repo.
- Make the needed dependencies installations (apt-get install or whatever)
- If unique user needs to be created, then create it
- Make the needed arrangements for password and auth for our DB.
- Create a basic schema / DB for our needs. No need to populate it with data just yet.

acceptance criteria:

- DB is running in a separate docker container
- DB container and web app can communicate
- Test added to check whether the DB container is up and running

### PR DESCRIPTION
**Pull request by IlanZuckerman**
fix #216 
Test added to check whether it is running. Requirements updated along
with Docker file

### CODE REVIEW

**Comment by lioramilbaum** [comment]
Did we decide if maridadb is the technology we want to go with?

**Comment by IlanZuckerman** [comment]
> Did we decide if maridadb is the technology we want to go with?

Yes. Decided.

**Comment by lioramilbaum** [comment]
Who was involved in the decision besides you? I am asking this because I don't think I was included.

**Comment by IlanZuckerman** [comment]
Since we decided to move on with PostgreSQL, I opened a new issue here:
https://github.com/beyond-io/beyond/pull/220

**Comment by lioramilbaum** [comment]
Do we need this PR?

**Comment by IlanZuckerman** [comment]
Closing this, as we decided to move on with PostgreSQL, I opened a new issue here:
#220

**Pull request closed without merging**
