### PR TITLE
Add content to html Home page and the main page links

### PR DESCRIPTION
**Pull request by rliberma**
Hi . 
Home page content is updated + i fixed the linked for the other page as to the high level topics we agreed.
I also removed housmade legacy content (-: 

Please review and approved. 
Thanks!

### CODE REVIEW

**Review by ipolonsk — COMMENTED** [review]
LGTM

**Comment by rliberma** [comment]
@IlanZuckerman @ipolonsk Can you please click on the approval button this will merge the change automatically to the master branch. Thanks!

**Review by ipolonsk — APPROVED** [review]
LGTM

**Review by lioramilbaum — APPROVED** [review]
LGTM

**Comment by lioramilbaum** [comment]
I have spinned a dev environment. It is broken for me. http://localhost:80 doesn't work.

**Pull request merged**
